# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-18 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0)),
                ('developer', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0)),
                ('reviewsnumber', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('picture1', models.ImageField(upload_to='devices_images')),
                ('picture2', models.ImageField(upload_to='devices_images')),
                ('picture3', models.ImageField(upload_to='devices_images')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('content', models.CharField(max_length=140)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iVR.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('likesnumber', models.IntegerField(default=0)),
                ('commentsnumber', models.IntegerField(default=0)),
                ('picture', models.ImageField(upload_to='feeds_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=140)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iVR.Feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iVR.Feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(default=0)),
                ('developer', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0)),
                ('reviewsnumber', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('picture1', models.ImageField(upload_to='games_images')),
                ('picture2', models.ImageField(upload_to='games_images')),
                ('picture3', models.ImageField(upload_to='games_images')),
            ],
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('content', models.CharField(max_length=140)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iVR.Device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('commentsnumber', models.IntegerField(default=0)),
                ('picture', models.ImageField(upload_to='news_images')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=140)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iVR.News')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('developer', models.CharField(max_length=20)),
                ('score', models.FloatField(default=0)),
                ('reviewsnumber', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('picture1', models.ImageField(upload_to='videos_images')),
                ('picture2', models.ImageField(upload_to='videos_images')),
                ('picture3', models.ImageField(upload_to='videos_images')),
            ],
        ),
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('content', models.CharField(max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iVR.Device')),
            ],
        ),
    ]
