# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-18 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iVR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='picture1',
            field=models.ImageField(upload_to='static/devices_images'),
        ),
        migrations.AlterField(
            model_name='device',
            name='picture2',
            field=models.ImageField(upload_to='static/devices_images'),
        ),
        migrations.AlterField(
            model_name='device',
            name='picture3',
            field=models.ImageField(upload_to='static/devices_images'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='picture',
            field=models.ImageField(upload_to='static/feeds_images'),
        ),
        migrations.AlterField(
            model_name='game',
            name='picture1',
            field=models.ImageField(upload_to='static/games_images'),
        ),
        migrations.AlterField(
            model_name='game',
            name='picture2',
            field=models.ImageField(upload_to='static/games_images'),
        ),
        migrations.AlterField(
            model_name='game',
            name='picture3',
            field=models.ImageField(upload_to='static/games_images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(upload_to='static/news_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/profile_images'),
        ),
        migrations.AlterField(
            model_name='video',
            name='picture1',
            field=models.ImageField(upload_to='static/videos_images'),
        ),
        migrations.AlterField(
            model_name='video',
            name='picture2',
            field=models.ImageField(upload_to='static/videos_images'),
        ),
        migrations.AlterField(
            model_name='video',
            name='picture3',
            field=models.ImageField(upload_to='static/videos_images'),
        ),
    ]
