# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-24 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iVR', '0002_auto_20160718_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='description',
            new_name='devicedescription',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='description',
            new_name='gamedescription',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='description',
            new_name='videodescription',
        ),
        migrations.AlterField(
            model_name='device',
            name='developer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='video',
            name='developer',
            field=models.CharField(max_length=30),
        ),
    ]
