# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-01 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iVR', '0007_auto_20160725_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='picture',
            field=models.ImageField(default='static/profile_images/ivr.png', upload_to='static/feeds_images'),
        ),
    ]
