# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-01 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iVR', '0008_auto_20160801_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='picture',
            field=models.ImageField(upload_to='static/feeds_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='static/profile_images/ivr.png', upload_to='static/profile_images'),
        ),
    ]
