# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-09 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iVR', '0010_auto_20160804_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followsnumber',
            new_name='followersnumber',
        ),
    ]
