# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-10 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iVR', '0011_auto_20160809_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followersnumber',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='followingnumber',
        ),
    ]
