# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iVR', '0014_auto_20160812_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='picture',
            field=models.ImageField(blank=True, default=' ', upload_to='static/feeds_images'),
        ),
    ]
