# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-14 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iVR', '0015_auto_20160812_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
